export const products = [
    // --- Men ---
    {
        id: 1,
        image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
        title: "Men's Casual Shirt",
        description: "A stylish casual shirt perfect for everyday wear.",
        category: "men",
        stock: 10,
    },
    {
        id: 2,
        image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
        title: "Men's Denim Jeans",
        description: "Comfortable and durable denim jeans with a modern fit.",
        category: "men",
        stock: 15,
    },
    {
        id: 3,
        image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
        title: "Men's Hoodie",
        description: "Warm and soft hoodie ideal for cooler weather.",
        category: "men",
        stock: 8,
    },
    {
        id: 4,
        image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
        title: "Men's Formal Blazer",
        description: "Elegant blazer suitable for office and formal occasions.",
        category: "men",
        stock: 5,
    },
    {
        id: 5,
        image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
        title: "Men's Sports T-Shirt",
        description: "Breathable athletic t-shirt for training and workouts.",
        category: "men",
        stock: 20,
    },

    // --- Women ---
    {
        id: 6,
        image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
        title: "Women's Summer Dress",
        description: "Lightweight floral dress, perfect for summer days.",
        category: "women",
        stock: 12,
    },
    {
        id: 7,
        image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_.jpg",
        title: "Women's High-Waisted Jeans",
        description: "Trendy jeans with a flattering high-rise fit.",
        category: "women",
        stock: 18,
    },
    {
        id: 8,
        image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
        title: "Women's Cardigan Sweater",
        description: "Cozy knit cardigan for layering during chilly days.",
        category: "women",
        stock: 7,
    },
    {
        id: 9,
        image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
        title: "Women's Workout Leggings",
        description: "Stretchy leggings ideal for yoga and workouts.",
        category: "women",
        stock: 25,
    },
    {
        id: 10,
        image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
        title: "Women's Evening Gown",
        description: "Elegant gown perfect for formal events and parties.",
        category: "women",
        stock: 4,
    },

    // --- Kids (Using Picsum as fallback for generic kids clothes) ---
    {
        id: 11,
        image: "https://picsum.photos/id/237/400/500",
        title: "Kids' Graphic T-Shirt",
        description: "Fun and colorful t-shirt for everyday play.",
        category: "kids",
        stock: 30,
    },
    {
        id: 12,
        image: "https://picsum.photos/id/1027/400/500",
        title: "Kids' Denim Overalls",
        description: "Classic overalls for active kids, easy to wear.",
        category: "kids",
        stock: 14,
    },
    {
        id: 13,
        image: "https://picsum.photos/id/1005/400/500",
        title: "Kids' Winter Jacket",
        description: "Warm and waterproof jacket for cold weather.",
        category: "kids",
        stock: 9,
    },
    {
        id: 14,
        image: "https://picsum.photos/id/1003/400/500",
        title: "Kids' Pajama Set",
        description: "Soft and comfy pajama set for a good night’s sleep.",
        category: "kids",
        stock: 22,
    },
    {
        id: 15,
        image: "https://picsum.photos/id/1011/400/500",
        title: "Kids' Party Dress",
        description: "Adorable dress for birthdays and special occasions.",
        category: "kids",
        stock: 6,
    },
];
